### ISSUE TITLE
Paired-end reads

### ISSUE THREAD

**Issue by simone-pignotti** [phac-nml/ecoli_serotyping#75]
Hi,

I think one of the useful features of ectyper is the support of paired end reads, and if I understand it correctly there is no paired-end support (FASTQs need to be concatenated together). Using the paired-end information could improve the precision of the tool. Do you have any plan on implementing that?

Thanks for this fast and useful tool!

Simone

**Comment by kbessonov1984** [comment]
Hi Simone,
We are rushing right now to release the new version of the tool and then get feedback from end-users like you to make it better. The ecTyper uses bwa aligner to align raw reads against reference alleles. So we just concat forward and reverse reads and do prediction from there. I agree that treating reads as a paired set could improve performance a bit. Based on our tests on PulseNet Canada and EnteroBase datasets the difference between assembled and raw reads (treated in as one set for now) did not produce any noticeable performance differences (the only handful of samples were miscalled). Still, for highest possible prediction power we recommend assembling raw reads (e.g. with unicycler) and then running ecTyper on them. It is especially true for highly similar O-antigens like O17/O77/O73 (see a nice publication on the topic [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0147434#pone.0147434.s002)). If you use Galaxy, you can easily create a workflow that will assembly and type E.coli isolates. The new version 0.9.0 will also have a QC flag and confidence level for the prediction. 

In the next release, I plan to improve on Illumina paired-end reads handling by the tool for users who do not have computational resources to assemble genomes.

**Comment by simone-pignotti** [comment]
Hi Kirill,

Thanks for the quick reply and the additional info. I was actually testing differences between raw and assembled predictions, so I am glad to know there is not much difference. My conjecture is that on low coverage samples, where assembly parameters could be too stringent, the raw reads give a better result when a reference is available.
I also agree that the improvement given by paired reads would be limited, it was more of a curiosity (e.g. if I was missing some option). Feel free to close this issue!

Thanks again
Simone

**Comment by kbessonov1984** [comment]
Our recommendation is to assemble Illumina paired-reads via shovill or spades assembler without any coverage requirement to avoid any raw reads filtering (i.e. in shovill  set `--mincov 0` and spades `--cov-cutoff off`). Other assemblers like `unicycler` filter reads on coverage and might result in truncated target alleles.
