### ISSUE TITLE
Genome name not extracted from filepath

### ISSUE THREAD

**Issue by JanMoat** [phac-nml/ecoli_serotyping#76]
The genome name is not being extracted from the filepath. I'm using version 0.9.0 via Conda.

Running `$ ectyper -i /path/to/file/ECR.fasta` has the following error:

```
Traceback (most recent call last):
  File ".../ectyper", line 13, in <module>
    ectyper.run_program()
  File ".../ectyper.py", line 101, in run_program
    args
  File ".../genomeFunctions.py", line 115, in get_genome_names_from_files
    files_dict[sample]["modheaderfile"] = r["newfile"]
KeyError: 'ECR'
```

The files_dict is
`{'/path/to/file/ECR.fasta': {'species': 'Escherichia coli', 'filepath': '/path/to/file/ECR.fasta'}}`

The expected files_dict is
`{'ECR': {'species': 'Escherichia coli', 'filepath': '/path/to/file/ECR.fasta'}}`

**Comment by kbessonov1984** [comment]
Thank you for reporting. I am aware of this bug. It will be addressed in version 0.9.1. Use --verify flag to overcome this issue.

**Comment by kbessonov1984** [comment]
@JanMoat Let us know if the issue was solved. Sorry for inconvenience and thank you for reporting as we are in the processing of validation and need to iron all potential bugs.

**Comment by kbessonov1984** [comment]
Version 0.9.1 should resolve this issue
