### ISSUE TITLE
-o argument is required

### ISSUE THREAD

**Issue by mediator01** [phac-nml/ecoli_serotyping#89]
Hello,
I recommend to add in the instruction that -o argument is required. On my system without the output dir specified, I got the error
"TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Adding the -o argument solved the issue.

**Comment by kbessonov1984** [comment]
The version 2.0.0 automatically generates output folder path if no `-o` is specified in the directory where the tool is run following the naming format `ectyper_<date>_<time>` format. I had also written unit tests to check this condition.
